Repository wisemen-digital/wisemen-flutter-packages, pull requests merged in 2025-04, with the labels that each got.

#25 Changed dialogs, added tests for dialogs, changed util test
  packages/sandbox/ios/Podfile.lock
  packages/sandbox/lib/features/settings/controllers/settings_controller.dart
  packages/sandbox/lib/features/settings/views/other_settings_screen.dart
  packages/sandbox/lib/features/settings/views/settings_screen.dart
  packages/sandbox/lib/features/shared/utils/alert_utils.dart
  packages/sandbox/lib/features/shared/utils/error_utils.dart
  packages/sandbox/lib/features/shared/utils/utils.dart
  packages/sandbox/lib/theme/app_theme.dart
  packages/sandbox/pubspec.yaml
  packages/wisecore/lib/src/dialogs/alert_dialog.dart
  packages/wisecore/lib/src/dialogs/alert_dialog_helper.dart
  packages/wisecore/lib/src/dialogs/dialog_button.dart
  packages/wisecore/lib/src/dialogs/dialog_button_option.dart
  packages/wisecore/lib/src/dialogs/dialogs.dart
  packages/wisecore/lib/src/dialogs/error_dialog.dart
  packages/wisecore/lib/src/dialogs/error_dialog_helper.dart
  packages/wisecore/lib/src/dialogs/platform_alert_service.dart
  packages/wisecore/test/dialogs/alert_dialog_test.dart
  packages/wisecore/test/dialogs/dialog_button_test.dart
  packages/wisecore/test/dialogs/dialog_test.dart
  packages/wisecore/test/dialogs/error_dialog_test.dart
  packages/wisecore/test/utils/wise_launcher_test.dart
Labels: 📃 XL PR, ✨ feature

#26 Sorry kevin
  packages/wisecore/CHANGELOG.md
  packages/wisecore/pubspec.yaml
  packages/wisecore/test/utils/wise_launcher_test.dart
Labels: 📃 XS PR

#27 Update Flutter Secure Storage to improve compatibility with newer sam…
  packages/wiseclient/CHANGELOG.md
  packages/wiseclient/pubspec.yaml
  packages/wisewidgetslibrary/CHANGELOG.md
  packages/wisewidgetslibrary/pubspec.yaml
Labels: 🛠️ bugfix, 📃 XS PR

#28 Remove deprecated bool
  packages/wiseclient/lib/src/secure_token_storage/fresh_secure_token_storage.dart
Labels: 🛠️ bugfix, 📃 XS PR
